name: to_do_list
description: TO DO LIST

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^4.0.5
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  firebase_core: ^2.13.0
  google_sign_in: ^5.4.4
  syncfusion_flutter_datepicker: ^21.2.6
  flutter_date_pickers: ^0.4.2
  intl: ^0.18.0
  expandable: ^5.0.1
  uuid: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
